# building from Alpine Linux
FROM alpine:3.12

# 1
RUN apk update && \
	apk add vim wget curl libc6-compat

# 2
RUN wget https://dl.grafana.com/oss/release/grafana-7.2.0.linux-amd64.tar.gz
RUN tar -zxvf grafana-7.2.0.linux-amd64.tar.gz

# 3
COPY ./grafana.db ./grafana-7.2.0/data/grafana.db

# 4
EXPOSE 3000

# 5
WORKDIR grafana-7.2.0
CMD ./bin/grafana-server
