# building from Alpine Linux
FROM alpine:3.12

# 1
RUN apk update && apk upgrade && \
	apk add nginx && \
	apk add openssl && \
	apk add openssh 

# 2
RUN mkdir /var/run/nginx && mkdir /www

#3
RUN adduser -D -g 'www' www

# 4
RUN chown -R www:www /var/lib/nginx && \
	chown -R www:www /www

# 5
RUN openssl req -x509 -nodes -days 365 -newkey rsa:4096 -subj '/C=NL/ST=Noord-Holland/O=Codam/CN=kubernetes' \
	-keyout /etc/ssl/nginx.key -out /etc/ssl/nginx.crt

# 6
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /www/index.html 
COPY sshd_config /etc/ssh/sshd_config

# 7
run adduser -h / -D sfeith && \
	echo "sfeith:halloGoed!1" | chpasswd		

# 8
COPY start.sh /start.sh

#9
RUN chmod +x ./start.sh

# 10
EXPOSE 22 80 443

# 11
CMD ./start.sh