apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      serviceAccount: sfeith
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          name: ftp-data
        - containerPort: 21
          name: ftps
        - containerPort: 10000
          name: drie
        - containerPort: 10001
          name: vier
        - containerPort: 10002
          name: vijf
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
spec:
  ports:  
  - name: ftp-data
    port: 20
    protocol: TCP
    targetPort: 20 
  - name: ftps
    port: 21
    protocol: TCP
    targetPort: 21
  - name: drie
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: vier
    port: 10001
    protocol: TCP
    targetPort: 10001
  - name: vijf
    port: 10003
    protocol: TCP
    targetPort: 10003
  selector:
    app: ftps
  type: LoadBalancer
